# Generated by Django 4.2.5 on 2023-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='codigo_sucursal',
            field=models.CharField(default='000000', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(default='Tienda Prueba', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ventas_a_cliente',
            unique_together={('sucursal_venta', 'documento_venta')},
        ),
    ]
