# Generated by Django 4.2.5 on 2023-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_sales', '0003_alter_ventas_a_cliente_documento_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_sucursal',
            field=models.CharField(default='Codigo', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(default='Nombre', max_length=100, unique=True),
        ),
    ]
