# Generated by Django 4.2.5 on 2023-09-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
