# Generated by Django 4.2.5 on 2023-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0002_alter_cliente_nit_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria_cliente',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descuento_autorizado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
