# Generated by Django 4.2.5 on 2023-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0003_cliente_categoria_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nit',
            new_name='documento_identidad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro_negocio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_registro_contribuyente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
