# Generated by Django 4.2.5 on 2023-09-22 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_data', '0004_rename_nit_cliente_documento_identidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giro_Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre_giro_negocio', models.CharField(default='Giro de Negocio', max_length=100, unique=True)),
                ('codigo_giro_negocio', models.CharField(default='Codigo de Actividad', max_length=10, unique=True)),
                ('creo', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifico', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giro de Negocio',
                'verbose_name_plural': 'Giros de Negocio',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='giro_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_data.giro_negocio'),
        ),
    ]
