# Generated by Django 4.2.5 on 2023-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0005_giro_negocio_alter_cliente_giro_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giro_negocio',
            name='nombre_giro_negocio',
            field=models.CharField(default='Giro de Negocio', max_length=200, unique=True),
        ),
    ]
